//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Web365.NL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NGANLUONG_APIBinding", Namespace="NS")]
    public partial class NGANLUONG_API : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetExpressCheckoutDepositOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetExpressCheckoutPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExpressCheckoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExpressCheckout2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NGANLUONG_API() {
            this.Url = global::Web365.Properties.Settings.Default.Web365_NL_NGANLUONG_API;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetExpressCheckoutDepositCompletedEventHandler SetExpressCheckoutDepositCompleted;
        
        /// <remarks/>
        public event SetExpressCheckoutPaymentCompletedEventHandler SetExpressCheckoutPaymentCompleted;
        
        /// <remarks/>
        public event GetExpressCheckoutCompletedEventHandler GetExpressCheckoutCompleted;
        
        /// <remarks/>
        public event GetExpressCheckout2CompletedEventHandler GetExpressCheckout2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.nganluong.vn/micro_checkout_api.php/SetExpressCheckoutDeposit", RequestNamespace="NS", ResponseNamespace="NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string SetExpressCheckoutDeposit(string merchant_site_code, string checksum, string @params) {
            object[] results = this.Invoke("SetExpressCheckoutDeposit", new object[] {
                        merchant_site_code,
                        checksum,
                        @params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetExpressCheckoutDepositAsync(string merchant_site_code, string checksum, string @params) {
            this.SetExpressCheckoutDepositAsync(merchant_site_code, checksum, @params, null);
        }
        
        /// <remarks/>
        public void SetExpressCheckoutDepositAsync(string merchant_site_code, string checksum, string @params, object userState) {
            if ((this.SetExpressCheckoutDepositOperationCompleted == null)) {
                this.SetExpressCheckoutDepositOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetExpressCheckoutDepositOperationCompleted);
            }
            this.InvokeAsync("SetExpressCheckoutDeposit", new object[] {
                        merchant_site_code,
                        checksum,
                        @params}, this.SetExpressCheckoutDepositOperationCompleted, userState);
        }
        
        private void OnSetExpressCheckoutDepositOperationCompleted(object arg) {
            if ((this.SetExpressCheckoutDepositCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetExpressCheckoutDepositCompleted(this, new SetExpressCheckoutDepositCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.nganluong.vn/micro_checkout_api.php/SetExpressCheckoutPayment", RequestNamespace="NS", ResponseNamespace="NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string SetExpressCheckoutPayment(string merchant_site_code, string checksum, string @params) {
            object[] results = this.Invoke("SetExpressCheckoutPayment", new object[] {
                        merchant_site_code,
                        checksum,
                        @params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetExpressCheckoutPaymentAsync(string merchant_site_code, string checksum, string @params) {
            this.SetExpressCheckoutPaymentAsync(merchant_site_code, checksum, @params, null);
        }
        
        /// <remarks/>
        public void SetExpressCheckoutPaymentAsync(string merchant_site_code, string checksum, string @params, object userState) {
            if ((this.SetExpressCheckoutPaymentOperationCompleted == null)) {
                this.SetExpressCheckoutPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetExpressCheckoutPaymentOperationCompleted);
            }
            this.InvokeAsync("SetExpressCheckoutPayment", new object[] {
                        merchant_site_code,
                        checksum,
                        @params}, this.SetExpressCheckoutPaymentOperationCompleted, userState);
        }
        
        private void OnSetExpressCheckoutPaymentOperationCompleted(object arg) {
            if ((this.SetExpressCheckoutPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetExpressCheckoutPaymentCompleted(this, new SetExpressCheckoutPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.nganluong.vn/micro_checkout_api.php/GetExpressCheckout", RequestNamespace="NS", ResponseNamespace="NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string GetExpressCheckout(string merchant_site_code, string checksum, string @params) {
            object[] results = this.Invoke("GetExpressCheckout", new object[] {
                        merchant_site_code,
                        checksum,
                        @params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetExpressCheckoutAsync(string merchant_site_code, string checksum, string @params) {
            this.GetExpressCheckoutAsync(merchant_site_code, checksum, @params, null);
        }
        
        /// <remarks/>
        public void GetExpressCheckoutAsync(string merchant_site_code, string checksum, string @params, object userState) {
            if ((this.GetExpressCheckoutOperationCompleted == null)) {
                this.GetExpressCheckoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExpressCheckoutOperationCompleted);
            }
            this.InvokeAsync("GetExpressCheckout", new object[] {
                        merchant_site_code,
                        checksum,
                        @params}, this.GetExpressCheckoutOperationCompleted, userState);
        }
        
        private void OnGetExpressCheckoutOperationCompleted(object arg) {
            if ((this.GetExpressCheckoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExpressCheckoutCompleted(this, new GetExpressCheckoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.nganluong.vn/micro_checkout_api.php/GetExpressCheckout2", RequestNamespace="NS", ResponseNamespace="NS")]
        [return: System.Xml.Serialization.SoapElementAttribute("result")]
        public string GetExpressCheckout2(string merchant_site_code, string checksum, string @params) {
            object[] results = this.Invoke("GetExpressCheckout2", new object[] {
                        merchant_site_code,
                        checksum,
                        @params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetExpressCheckout2Async(string merchant_site_code, string checksum, string @params) {
            this.GetExpressCheckout2Async(merchant_site_code, checksum, @params, null);
        }
        
        /// <remarks/>
        public void GetExpressCheckout2Async(string merchant_site_code, string checksum, string @params, object userState) {
            if ((this.GetExpressCheckout2OperationCompleted == null)) {
                this.GetExpressCheckout2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExpressCheckout2OperationCompleted);
            }
            this.InvokeAsync("GetExpressCheckout2", new object[] {
                        merchant_site_code,
                        checksum,
                        @params}, this.GetExpressCheckout2OperationCompleted, userState);
        }
        
        private void OnGetExpressCheckout2OperationCompleted(object arg) {
            if ((this.GetExpressCheckout2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExpressCheckout2Completed(this, new GetExpressCheckout2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetExpressCheckoutDepositCompletedEventHandler(object sender, SetExpressCheckoutDepositCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetExpressCheckoutDepositCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetExpressCheckoutDepositCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetExpressCheckoutPaymentCompletedEventHandler(object sender, SetExpressCheckoutPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetExpressCheckoutPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetExpressCheckoutPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetExpressCheckoutCompletedEventHandler(object sender, GetExpressCheckoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExpressCheckoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExpressCheckoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetExpressCheckout2CompletedEventHandler(object sender, GetExpressCheckout2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExpressCheckout2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExpressCheckout2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591