//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365BaseReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSumMoneyInHour
    {
        public int ID { get; set; }
        public Nullable<decimal> TongTienUser { get; set; }
        public Nullable<decimal> TongTienKetSatUser { get; set; }
        public Nullable<decimal> TongTienKetSat { get; set; }
        public Nullable<decimal> TongTienNickTongPoc { get; set; }
        public Nullable<decimal> TongTienKetSatNickTongPoc { get; set; }
        public Nullable<decimal> TongHu { get; set; }
        public Nullable<decimal> TongGameBank { get; set; }
        public Nullable<decimal> TongTienDaiLyCap1 { get; set; }
        public Nullable<decimal> TongTienKetSatDaiLyCap1 { get; set; }
        public Nullable<decimal> TongTienDaiLyCap2 { get; set; }
        public Nullable<decimal> TongTienKetSatDaiLyCap2 { get; set; }
        public Nullable<decimal> TongTienGiftCodeChuaNap { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> TongUser { get; set; }
        public Nullable<decimal> TongGiftCodeDaNap { get; set; }
        public Nullable<decimal> LoiNhuan { get; set; }
    }
}
