//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365BaseReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoogleMessage
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public string GoogleId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
