//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticleAuto
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Xpath { get; set; }
        public string XpathTitle { get; set; }
        public string XpathSummary { get; set; }
        public string XpathDetail { get; set; }
        public string XpathImage { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Xpage { get; set; }
        public string XpathPaging { get; set; }
        public string ListGroupArticle { get; set; }
    }
}
