//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGameLogsDetail
    {
        public int ID { get; set; }
        public Nullable<int> LogID { get; set; }
        public string Note { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string UserName { get; set; }
    }
}
