//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGameConfigLogs
    {
        public int ID { get; set; }
        public Nullable<int> gameId { get; set; }
        public Nullable<int> a { get; set; }
        public Nullable<int> a1 { get; set; }
        public Nullable<int> a2 { get; set; }
        public Nullable<int> a3 { get; set; }
        public Nullable<int> a4 { get; set; }
        public Nullable<int> a5 { get; set; }
        public Nullable<int> a6 { get; set; }
        public Nullable<int> a7 { get; set; }
        public Nullable<int> a8 { get; set; }
        public Nullable<int> a9 { get; set; }
        public Nullable<int> a10 { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> DateCreared { get; set; }
    }
}
